services:
  openproject:
    image: openproject/community:15
    container_name: openproject
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      - TZ=${TZ}
      - SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY}
      - OPENPROJECT_HOST__NAME=${APP_DOMAIN}
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_ADMIN_EMAIL=${OPENPROJECT_ADMIN_EMAIL}
      - OPENPROJECT_ADMIN_USERNAME=${OPENPROJECT_ADMIN_USERNAME}
      - OPENPROJECT_ADMIN_PASSWORD=${OPENPROJECT_ADMIN_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/pgdata:/var/openproject/pgdata
      - ${APP_DATA_DIR}/data/assets:/var/openproject/assets
    ports:
      - ${APP_PORT}:80
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.openproject-web-redirect.redirectscheme.scheme: https
      traefik.http.services.openproject.loadbalancer.server.port: "80"
      traefik.http.routers.openproject-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openproject-insecure.entrypoints: web
      traefik.http.routers.openproject-insecure.service: openproject
      traefik.http.routers.openproject-insecure.middlewares: openproject-web-redirect
      traefik.http.routers.openproject.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openproject.entrypoints: websecure
      traefik.http.routers.openproject.service: openproject
      traefik.http.routers.openproject.tls.certresolver: myresolver
      traefik.http.routers.openproject-local-insecure.rule: Host(`openproject.${LOCAL_DOMAIN}`)
      traefik.http.routers.openproject-local-insecure.entrypoints: web
      traefik.http.routers.openproject-local-insecure.service: openproject
      traefik.http.routers.openproject-local-insecure.middlewares: openproject-web-redirect
      traefik.http.routers.openproject-local.rule: Host(`openproject.${LOCAL_DOMAIN}`)
      traefik.http.routers.openproject-local.entrypoints: websecure
      traefik.http.routers.openproject-local.service: openproject
      traefik.http.routers.openproject-local.tls: true
      runtipi.managed: true

networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true