version: "3.9"
services:
  openproject:
    container_name: openproject
    image: openproject/community:13.0
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - OPENPROJECT_HOST__NAME=${APP_DOMAIN}
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_ADMIN_PASSWORD=${OPENPROJECT_ADMIN_PASSWORD}
      - OPENPROJECT_EDITION=standard
      - DATABASE_URL=postgres://postgres:postgres@openproject-db:5432/openproject
    volumes:
      - ${APP_DATA_DIR}/data/assets:/var/openproject/assets
    ports:
      - ${APP_PORT}:80
    depends_on:
      - openproject-db
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.openproject-web-redirect.redirectscheme.scheme: https
      traefik.http.services.openproject.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.openproject-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openproject-insecure.entrypoints: web
      traefik.http.routers.openproject-insecure.service: openproject
      traefik.http.routers.openproject-insecure.middlewares: openproject-web-redirect
      # Websecure
      traefik.http.routers.openproject.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openproject.entrypoints: websecure
      traefik.http.routers.openproject.service: openproject
      traefik.http.routers.openproject.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.openproject-local-insecure.rule: Host(`openproject.${LOCAL_DOMAIN}`)
      traefik.http.routers.openproject-local-insecure.entrypoints: web
      traefik.http.routers.openproject-local-insecure.service: openproject
      traefik.http.routers.openproject-local-insecure.middlewares: openproject-web-redirect
      # Local domain secure
      traefik.http.routers.openproject-local.rule: Host(`openproject.${LOCAL_DOMAIN}`)
      traefik.http.routers.openproject-local.entrypoints: websecure
      traefik.http.routers.openproject-local.service: openproject
      traefik.http.routers.openproject-local.tls: true

  openproject-db:
    container_name: openproject-db
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openproject
    volumes:
      - ${APP_DATA_DIR}/data/pgdata:/var/lib/postgresql/data
    networks:
      - tipi_main_network

networks:
  tipi_main_network:
    external: true